### ISSUE TITLE
API token field not appearing

### ISSUE THREAD

**Issue by pieterpoorthuis** [bitpay/gravityforms-plugin#10]
WP v4.7.2 , gravity forms v2.1.3, plugin version 2.0.2

API key field is not appearing. See screenshot for an example.
![image001](https://user-images.githubusercontent.com/13945200/31004251-e36397d6-a4f3-11e7-9cb2-8f411d318e68.jpg)

**Comment by Moondesk** [comment]
Hello I´m having the same issue did u found a solution ?
Thanks

**Comment by pieterpoorthuis** [comment]
Working on a new version, including a fix for this issue. Expect it to be ready in November 2017.

**Comment by pieterpoorthuis** [comment]
Fixed in release 2.03
