### ISSUE TITLE
Unable to pair with BitPay

### ISSUE THREAD

**Issue by wladston** [bitpay/gravityforms-plugin#8]
I tried pairing with API Tokens from both livenet and mainnet. In both cases, the plugin says "Unable to pair with BitPay", without any further explanation.

Any idea how we can debug this? I could try fixing the code given some guidance.

**Comment by outputninja** [comment]
I'm having an issue aswell,
Warning: file_get_contents(/templates/pairing.tpl): failed to open stream: HTTP request failed! HTTP/1.1 500 Internal Server Error in /srv/bindings/72cfaae7a2824616b13b94fc1459073e/code/wp-content/plugins/bitpay-gravityforms-plugin/views/admin-settings.php on line 19 Warning

**Comment by pieterpoorthuis** [comment]
Fixed in release 2.03
